name: add-@author
run-name: adding ${{ github.actor }} as author
on: [push]
jobs:
  add-author:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.requested_team.name }}
